FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Set working directory
WORKDIR /app

# Install Python 3.8 and common tools
RUN apt-get update && apt-get install -y \
    python3.8 \
    python3.8-venv \
    python3.8-distutils \
    python3-pip \
    curl \
    git \
    unzip \
    vim \
    wget \
    nano \
    net-tools \
    iputils-ping \
    dnsutils \
    build-essential \
    software-properties-common \
    && ln -sf /usr/bin/python3.8 /usr/bin/python3 \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
RUN pip install poetry==1.3.2

# Clone Repo
RUN git clone https://github.com/tqtensor/cot-selfevolve.git .

# Download and install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf awscliv2.zip aws

# Install tool
RUN poetry install
