import logging
import os

from subproccess_helper import run_shell

#from docker_helper import DockerHelper
#from subproccess_helper import run, run_shell

# Ensure the folder exists
os.makedirs('./out', exist_ok=True)

# Set up basic configuration for logging
logging.basicConfig(
    filename='./out/log.txt',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s',
    force=True
)
logging.debug("---Starting Setup---")
logging.info("---10. OpenCodeInterpreter---")
logging.info("---starting set up script---")
result = run_shell(f"./setup.sh", shell=True)
logging.debug(result["stdout"])
logging.info("---start server---")
from subproccess_helper import run_async

proc = run_async("conda", ["run", "-n", "opencode", "python3", "../10_open_code_interpreter/OpenCodeInterpreter/demo/chatbot.py",
                           "--path", "m-a-p/OpenCodeInterpreter-DS-6.7B"])

print("✅ Server started (PID:", proc.pid, ")")
# Python continues running here...
logging.info("---test server connection---")
import io
import logging
from contextlib import redirect_stdout
from gradio_client import Client

client = Client("https://22ebc1c4fb3274abc1.gradio.live/")

buf = io.StringIO()
with redirect_stdout(buf):
    client.view_api()

logging.info("Gradio API Info:\n%s", buf.getvalue())

logging.info("generating code")
result = client.predict(
		user_message="Give me a program that computes the first 100 prime numbers",
		api_name="/partial"
)
logging.info("code generated successfully")
logging.info(result)

import re

def extract_python_code(text: str) -> str:
    """
    Extracts the Python code block (```python ... ```) from a given text.
    Returns the code as a string, or None if no code block is found.
    """
    match = re.search(r"```python(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return None

def save_code_to_file(code: str, filename: str = "output.py"):
    """
    Saves the given Python code string to a file.
    """
    with open(filename, "w", encoding="utf-8") as f:
        f.write(code)
    print(f"✅ Code saved to {filename}")

# Example usage with your given response:
# response = [
#     ['Give me a program that computes the first 100 prime numbers',
#      'Here is a Python program that computes the first 100 prime numbers:\n\n```python\ndef is_prime(n):\n    if n <= 1:\n        return False\n    if n <= 3:\n        return True\n    if n % 2 == 0 or n % 3 == 0:\n        return False\n    i = 5\n    while i * i <= n:\n        if n % i == 0 or n % (i + 2) == 0:\n            return False\n        i += 6\n    return True\n\ndef get_primes(count):\n    primes = []\n    num = 2\n    while len(primes) < count:\n        if is_prime(num):\n            primes.append(num)\n        num += 1\n    return primes\n\nprimes = get_primes(100)\nprint(primes)\n```\n\nThis program uses a helper function `is_prime()` to check if a number is prime. It then uses another function `get_primes()` to generate the first 100 prime numbers. The `get_primes()` function uses a while loop to keep generating prime numbers until it has found the desired number of primes. Finally, it prints the list of the first 100 prime numbers.'],
#     ['Execution result: \n[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541]',
#      'The first 100 prime numbers are:\n\n[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541]\n\nThese numbers are generated by the program using the `is_prime()` function to check if each number is prime. The `get_primes()` function keeps generating prime numbers until it has found the desired number of primes.']
# ]

# Flatten response into a single string
response_text = " ".join(sum(result, []))

# Extract code
code = extract_python_code(response_text)

if code:
    save_code_to_file(code, "out/primes.py")
    logging.info(code)
    logging.info("Code saved to primes.py")
else:
    logging.info("No code found")
    print("❌ No Python code found in the response.")
